In [1]:
import pandas as pd
db=pd.read_csv("dataset.csv")

In [2]:
db.columns

Index(['id', 'title', 'category', 'category_code', 'published_date',
       'updated_date', 'authors', 'first_author', 'summary',
       'summary_word_count'],
      dtype='object')

In [3]:
db.head

<bound method NDFrame.head of                       id                                              title  \
0           cs-9308101v1                               Dynamic Backtracking
1           cs-9308102v1  A Market-Oriented Programming Environment and ...
2           cs-9309101v1            An Empirical Analysis of Search in GSAT
3           cs-9311101v1  The Difficulties of Learning Logic Programs wi...
4           cs-9311102v1  Software Agents: Completing Patterns and Const...
...                  ...                                                ...
136233  abs-2408.08541v1         Where is the signal in tokenization space?
136234  abs-2408.08564v1  Collaborative Cross-modal Fusion with Large La...
136235  abs-2408.08624v1  RealMedQA: A pilot biomedical question answeri...
136236  abs-2408.08648v1  Understanding Enthymemes in Argument Maps: Bri...
136237  abs-2408.08651v2  Reasoning Beyond Bias: A Study on Counterfactu...

                                                 category category_code  \
0                                 Artificial Intelligence         cs.AI
1                                 Artificial Intelligence         cs.AI
2                                 Artificial Intelligence         cs.AI
3                                 Artificial Intelligence         cs.AI
4                                 Artificial Intelligence         cs.AI
...                                                   ...           ...
136233  Computation and Language (Natural Language Pro...         cs.CL
136234                              Information Retrieval         cs.IR
136235  Computation and Language (Natural Language Pro...         cs.CL
136236                            Artificial Intelligence         cs.AI
136237  Computation and Language (Natural Language Pro...         cs.CL

       published_date updated_date  \
0              8/1/93       8/1/93
1              8/1/93       8/1/93
2              9/1/93       9/1/93
3             11/1/93      11/1/93
4             11/1/93      11/1/93
...               ...          ...
136233        8/16/24      8/16/24
136234        8/16/24      8/16/24
136235        8/16/24      8/16/24
136236        8/16/24      8/16/24
136237        8/16/24       9/6/24

                                                  authors  \
0                                      ['M. L. Ginsberg']
1                                       ['M. P. Wellman']
2                              ['I. P. Gent', 'T. Walsh']
3          ['F. Bergadano', 'D. Gunetti', 'U. Trinchero']
4                    ['J. C. Schlimmer', 'L. A. Hermens']
...                                                   ...
136233  ['Renato Lui Geh', 'Honghua Zhang', 'Kareem Ah...
136234  ['Zhongzhou Liu', 'Hao Zhang', 'Kuicai Dong', ...
136235  ['Gregory Kell', 'Angus Roberts', 'Serge Umans...
136236  ['Jonathan Ben-Naim', 'Victor David', 'Anthony...
136237  ['Kyle Moore', 'Jesse Roberts', 'Thao Pham', '...

               first_author  \
0          'M. L. Ginsberg'
1           'M. P. Wellman'
2              'I. P. Gent'
3            'F. Bergadano'
4         'J. C. Schlimmer'
...                     ...
136233     'Renato Lui Geh'
136234      'Zhongzhou Liu'
136235       'Gregory Kell'
136236  'Jonathan Ben-Naim'
136237         'Kyle Moore'

                                                  summary  summary_word_count
0       Because of their occasional need to return to ...                  79
1       Market price systems constitute a well-underst...                 119
2       We describe an extensive study of search in GS...                 167
3       As real logic programmers normally use cut (!)...                 174
4       To support the goal of allowing users to recor...                 187
...                                                   ...                 ...
136233  Large Language Models (LLMs) are typically shi...                 170
136234  Despite the success of conventional collaborat...                 157
136235  Clinical question answering systems have the p...                 153
136236  Argument mining is natural language processing...                 194
136237  Language models are known to absorb biases fro...                 156

[136238 rows x 10 columns]>

In [4]:
db[10:20]

,id,title,category,category_code,published_date,updated_date,authors,first_author,summary,summary_word_count
10,cs-9403101v1,Exploring the Decision Forest: An Empirical In...,Artificial Intelligence,cs.AI,3/1/94,3/1/94,"['P. M. Murphy', 'M. J. Pazzani']",'P. M. Murphy',We report on a series of experiments in which ...,122
11,cs-9406101v1,A Semantics and Complete Algorithm for Subsump...,Artificial Intelligence,cs.AI,6/1/94,6/1/94,"['A. Borgida', 'P. F. Patel-Schneider']",'A. Borgida',This paper analyzes the correctness of the sub...,109
12,cs-9406102v1,Applying GSAT to Non-Clausal Formulas,Artificial Intelligence,cs.AI,6/1/94,6/1/94,['R. Sebastiani'],'R. Sebastiani',In this paper we describe how to modify GSAT s...,75
13,cs-9408101v1,Random Worlds and Maximum Entropy,Artificial Intelligence,cs.AI,8/1/94,8/1/94,"['A. J. Grove', 'J. Y. Halpern', 'D. Koller']",'A. J. Grove',Given a knowledge base KB containing first-ord...,213
14,cs-9408102v1,Pattern Matching and Discourse Processing in I...,Artificial Intelligence,cs.AI,8/1/94,8/1/94,"['T. Kitani', 'Y. Eriguchi', 'M. Hara']",'T. Kitani',Information extraction is the task of automati...,170
15,cs-9408103v1,A System for Induction of Oblique Decision Trees,Artificial Intelligence,cs.AI,8/1/94,8/1/94,"['S. K. Murthy', 'S. Kasif', 'S. Salzberg']",'S. K. Murthy',This article describes a new system for induct...,111
16,cs-9409101v1,On Planning while Learning,Artificial Intelligence,cs.AI,9/1/94,9/1/94,"['S. Safra', 'M. Tennenholtz']",'S. Safra',This paper introduces a framework for Planning...,106
17,cs-9412101v1,Wrap-Up: a Trainable Discourse Module for Info...,Artificial Intelligence,cs.AI,12/1/94,12/1/94,"['S. Soderland', 'Lehnert. W']",'S. Soderland',The vast amounts of on-line text now available...,130
18,cs-9412102v1,Operations for Learning with Graphical Models,Artificial Intelligence,cs.AI,12/1/94,12/1/94,['W. L. Buntine'],'W. L. Buntine',This paper is a multidisciplinary review of em...,175
19,cs-9412103v1,Total-Order and Partial-Order Planning: A Comp...,Artificial Intelligence,cs.AI,12/1/94,12/1/94,"['S. Minton', 'J. Bresina', 'M. Drummond']",'S. Minton',"For many years, the intuitions underlying part...",107

In [5]:
new_df=db[['id', 'title','published_date','authors', 'first_author','summary']]

In [6]:
print(new_df)

                      id                                              title  \
0           cs-9308101v1                               Dynamic Backtracking
1           cs-9308102v1  A Market-Oriented Programming Environment and ...
2           cs-9309101v1            An Empirical Analysis of Search in GSAT
3           cs-9311101v1  The Difficulties of Learning Logic Programs wi...
4           cs-9311102v1  Software Agents: Completing Patterns and Const...
...                  ...                                                ...
136233  abs-2408.08541v1         Where is the signal in tokenization space?
136234  abs-2408.08564v1  Collaborative Cross-modal Fusion with Large La...
136235  abs-2408.08624v1  RealMedQA: A pilot biomedical question answeri...
136236  abs-2408.08648v1  Understanding Enthymemes in Argument Maps: Bri...
136237  abs-2408.08651v2  Reasoning Beyond Bias: A Study on Counterfactu...

       published_date                                            authors  \
0              8/1/93                                 ['M. L. Ginsberg']
1              8/1/93                                  ['M. P. Wellman']
2              9/1/93                         ['I. P. Gent', 'T. Walsh']
3             11/1/93     ['F. Bergadano', 'D. Gunetti', 'U. Trinchero']
4             11/1/93               ['J. C. Schlimmer', 'L. A. Hermens']
...               ...                                                ...
136233        8/16/24  ['Renato Lui Geh', 'Honghua Zhang', 'Kareem Ah...
136234        8/16/24  ['Zhongzhou Liu', 'Hao Zhang', 'Kuicai Dong', ...
136235        8/16/24  ['Gregory Kell', 'Angus Roberts', 'Serge Umans...
136236        8/16/24  ['Jonathan Ben-Naim', 'Victor David', 'Anthony...
136237        8/16/24  ['Kyle Moore', 'Jesse Roberts', 'Thao Pham', '...

               first_author                                            summary
0          'M. L. Ginsberg'  Because of their occasional need to return to ...
1           'M. P. Wellman'  Market price systems constitute a well-underst...
2              'I. P. Gent'  We describe an extensive study of search in GS...
3            'F. Bergadano'  As real logic programmers normally use cut (!)...
4         'J. C. Schlimmer'  To support the goal of allowing users to recor...
...                     ...                                                ...
136233     'Renato Lui Geh'  Large Language Models (LLMs) are typically shi...
136234      'Zhongzhou Liu'  Despite the success of conventional collaborat...
136235       'Gregory Kell'  Clinical question answering systems have the p...
136236  'Jonathan Ben-Naim'  Argument mining is natural language processing...
136237         'Kyle Moore'  Language models are known to absorb biases fro...

[136238 rows x 6 columns]

In [7]:
import numpy as np

for index, row in new_df.iterrows():
    if row['id'].startswith('cs-'):
        new_df.at[index, 'pdf_link'] = "https://arxiv.org/pdf/cs/" + row['id'][3:]
    else:
        new_df.at[index, 'pdf_link'] = np.nan

C:\Users\User\AppData\Local\Temp\ipykernel_20312\321651198.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.at[index, 'pdf_link'] = "https://arxiv.org/pdf/cs/" + row['id'][3:]

In [8]:
for index, row in new_df.iterrows():
    # access data

    if row['id'].startswith('cs-'):
        print(row['id'],row['pdf_link'])

cs-9308101v1 https://arxiv.org/pdf/cs/9308101v1
cs-9308102v1 https://arxiv.org/pdf/cs/9308102v1
cs-9309101v1 https://arxiv.org/pdf/cs/9309101v1
cs-9311101v1 https://arxiv.org/pdf/cs/9311101v1
cs-9311102v1 https://arxiv.org/pdf/cs/9311102v1
cs-9312101v1 https://arxiv.org/pdf/cs/9312101v1
cs-9401101v1 https://arxiv.org/pdf/cs/9401101v1
cs-9402101v1 https://arxiv.org/pdf/cs/9402101v1
cs-9402102v1 https://arxiv.org/pdf/cs/9402102v1
cs-9402103v1 https://arxiv.org/pdf/cs/9402103v1
cs-9403101v1 https://arxiv.org/pdf/cs/9403101v1
cs-9406101v1 https://arxiv.org/pdf/cs/9406101v1
cs-9406102v1 https://arxiv.org/pdf/cs/9406102v1
cs-9408101v1 https://arxiv.org/pdf/cs/9408101v1
cs-9408102v1 https://arxiv.org/pdf/cs/9408102v1
cs-9408103v1 https://arxiv.org/pdf/cs/9408103v1
cs-9409101v1 https://arxiv.org/pdf/cs/9409101v1
cs-9412101v1 https://arxiv.org/pdf/cs/9412101v1
cs-9412102v1 https://arxiv.org/pdf/cs/9412102v1
cs-9412103v1 https://arxiv.org/pdf/cs/9412103v1
cs-9501101v1 https://arxiv.org/pdf/cs/9501101v1
cs-9501102v1 https://arxiv.org/pdf/cs/9501102v1
cs-9501103v1 https://arxiv.org/pdf/cs/9501103v1
cs-9503102v1 https://arxiv.org/pdf/cs/9503102v1
cs-9504101v1 https://arxiv.org/pdf/cs/9504101v1
cs-9505101v1 https://arxiv.org/pdf/cs/9505101v1
cs-9505102v1 https://arxiv.org/pdf/cs/9505102v1
cs-9505103v1 https://arxiv.org/pdf/cs/9505103v1
cs-9505104v1 https://arxiv.org/pdf/cs/9505104v1
cs-9505105v1 https://arxiv.org/pdf/cs/9505105v1
cs-9506101v1 https://arxiv.org/pdf/cs/9506101v1
cs-9506102v1 https://arxiv.org/pdf/cs/9506102v1
cs-9507101v1 https://arxiv.org/pdf/cs/9507101v1
cs-9508101v1 https://arxiv.org/pdf/cs/9508101v1
cs-9508102v1 https://arxiv.org/pdf/cs/9508102v1
cs-9510101v1 https://arxiv.org/pdf/cs/9510101v1
cs-9510102v1 https://arxiv.org/pdf/cs/9510102v1
cs-9510103v1 https://arxiv.org/pdf/cs/9510103v1
cs-9511101v1 https://arxiv.org/pdf/cs/9511101v1
cs-9512101v1 https://arxiv.org/pdf/cs/9512101v1
cs-9512102v1 https://arxiv.org/pdf/cs/9512102v1
cs-9512103v1 https://arxiv.org/pdf/cs/9512103v1
cs-9512104v1 https://arxiv.org/pdf/cs/9512104v1
cs-9512105v1 https://arxiv.org/pdf/cs/9512105v1
cs-9512106v1 https://arxiv.org/pdf/cs/9512106v1
cs-9512107v1 https://arxiv.org/pdf/cs/9512107v1
cs-9601101v1 https://arxiv.org/pdf/cs/9601101v1
cs-9602101v1 https://arxiv.org/pdf/cs/9602101v1
cs-9602102v1 https://arxiv.org/pdf/cs/9602102v1
cs-9603101v1 https://arxiv.org/pdf/cs/9603101v1
cs-9603102v1 https://arxiv.org/pdf/cs/9603102v1
cs-9603103v1 https://arxiv.org/pdf/cs/9603103v1
cs-9603104v1 https://arxiv.org/pdf/cs/9603104v1
cs-9604101v1 https://arxiv.org/pdf/cs/9604101v1
cs-9604102v1 https://arxiv.org/pdf/cs/9604102v1
cs-9604103v1 https://arxiv.org/pdf/cs/9604103v1
cs-9605101v1 https://arxiv.org/pdf/cs/9605101v1
cs-9605102v1 https://arxiv.org/pdf/cs/9605102v1
cs-9605103v1 https://arxiv.org/pdf/cs/9605103v1
cs-9605104v1 https://arxiv.org/pdf/cs/9605104v1
cs-9605105v1 https://arxiv.org/pdf/cs/9605105v1
cs-9605106v1 https://arxiv.org/pdf/cs/9605106v1
cs-9606101v1 https://arxiv.org/pdf/cs/9606101v1
cs-9606102v1 https://arxiv.org/pdf/cs/9606102v1
cs-9608103v1 https://arxiv.org/pdf/cs/9608103v1
cs-9608104v1 https://arxiv.org/pdf/cs/9608104v1
cs-9609101v1 https://arxiv.org/pdf/cs/9609101v1
cs-9609102v1 https://arxiv.org/pdf/cs/9609102v1
cs-9610101v1 https://arxiv.org/pdf/cs/9610101v1
cs-9610102v1 https://arxiv.org/pdf/cs/9610102v1
cs-9611101v1 https://arxiv.org/pdf/cs/9611101v1
cs-9612101v1 https://arxiv.org/pdf/cs/9612101v1
cs-9612102v1 https://arxiv.org/pdf/cs/9612102v1
cs-9612103v1 https://arxiv.org/pdf/cs/9612103v1
cs-9701101v1 https://arxiv.org/pdf/cs/9701101v1
cs-9701102v1 https://arxiv.org/pdf/cs/9701102v1
cs-9703101v1 https://arxiv.org/pdf/cs/9703101v1
cs-9704101v1 https://arxiv.org/pdf/cs/9704101v1
cs-9705101v1 https://arxiv.org/pdf/cs/9705101v1
cs-9705102v1 https://arxiv.org/pdf/cs/9705102v1
cs-9706101v1 https://arxiv.org/pdf/cs/9706101v1
cs-9706102v1 https://arxiv.org/pdf/cs/9706102v1
cs-9707101v1 https://arxiv.org/pdf/cs/9707101v1
cs-9707102v1 https://arxiv.org/pdf/cs/9707102v1
cs-9707103v1 https://arxiv.org/pdf/cs/9707103v1
cs-9709101v1 https://arxiv.org/pdf/cs/9709101v1
cs-9709102v1 https://arxiv.org/pdf/cs/9709102v1
cs-9711102v1 https://arxiv.org/pdf/cs/9711102v1
cs-9711103v1 https://arxiv.org/pdf/cs/9711103v1
cs-9711104v1 https://arxiv.org/pdf/cs/9711104v1
cs-9712101v1 https://arxiv.org/pdf/cs/9712101v1
cs-9712102v1 https://arxiv.org/pdf/cs/9712102v1
cs-9801101v1 https://arxiv.org/pdf/cs/9801101v1
cs-9801102v1 https://arxiv.org/pdf/cs/9801102v1
cs-9803101v1 https://arxiv.org/pdf/cs/9803101v1
cs-9803102v1 https://arxiv.org/pdf/cs/9803102v1
cs-9803103v1 https://arxiv.org/pdf/cs/9803103v1
cs-9805101v1 https://arxiv.org/pdf/cs/9805101v1
cs-9806101v1 https://arxiv.org/pdf/cs/9806101v1
cs-9806102v1 https://arxiv.org/pdf/cs/9806102v1
cs-9808101v1 https://arxiv.org/pdf/cs/9808101v1
cs-9810016v1 https://arxiv.org/pdf/cs/9810016v1
cs-9811024v1 https://arxiv.org/pdf/cs/9811024v1
cs-9812010v1 https://arxiv.org/pdf/cs/9812010v1
cs-9812017v1 https://arxiv.org/pdf/cs/9812017v1
cs-9903016v1 https://arxiv.org/pdf/cs/9903016v1
cs-9906002v1 https://arxiv.org/pdf/cs/9906002v1
cs-9909003v1 https://arxiv.org/pdf/cs/9909003v1
cs-9910016v1 https://arxiv.org/pdf/cs/9910016v1
cs-9911012v2 https://arxiv.org/pdf/cs/9911012v2
cs-0002002v1 https://arxiv.org/pdf/cs/0002002v1
cs-0002003v1 https://arxiv.org/pdf/cs/0002003v1
cs-0002009v1 https://arxiv.org/pdf/cs/0002009v1
cs-0003008v1 https://arxiv.org/pdf/cs/0003008v1
cs-0003012v1 https://arxiv.org/pdf/cs/0003012v1
cs-0003016v1 https://arxiv.org/pdf/cs/0003016v1
cs-0003020v2 https://arxiv.org/pdf/cs/0003020v2
cs-0003021v1 https://arxiv.org/pdf/cs/0003021v1
cs-0003023v1 https://arxiv.org/pdf/cs/0003023v1
cs-0003024v1 https://arxiv.org/pdf/cs/0003024v1
cs-0003027v1 https://arxiv.org/pdf/cs/0003027v1
cs-0003028v1 https://arxiv.org/pdf/cs/0003028v1
cs-0003029v1 https://arxiv.org/pdf/cs/0003029v1
cs-0003030v1 https://arxiv.org/pdf/cs/0003030v1
cs-0003031v1 https://arxiv.org/pdf/cs/0003031v1
cs-0003032v1 https://arxiv.org/pdf/cs/0003032v1
cs-0003033v1 https://arxiv.org/pdf/cs/0003033v1
cs-0003034v2 https://arxiv.org/pdf/cs/0003034v2
cs-0003037v1 https://arxiv.org/pdf/cs/0003037v1
cs-0003038v1 https://arxiv.org/pdf/cs/0003038v1
cs-0003039v1 https://arxiv.org/pdf/cs/0003039v1
cs-0003042v1 https://arxiv.org/pdf/cs/0003042v1
cs-0003044v1 https://arxiv.org/pdf/cs/0003044v1
cs-0003047v1 https://arxiv.org/pdf/cs/0003047v1
cs-0003049v1 https://arxiv.org/pdf/cs/0003049v1
cs-0003051v1 https://arxiv.org/pdf/cs/0003051v1
cs-0003052v3 https://arxiv.org/pdf/cs/0003052v3
cs-0003059v1 https://arxiv.org/pdf/cs/0003059v1
cs-0003061v1 https://arxiv.org/pdf/cs/0003061v1
cs-0003077v1 https://arxiv.org/pdf/cs/0003077v1
cs-0003080v1 https://arxiv.org/pdf/cs/0003080v1
cs-0005031v3 https://arxiv.org/pdf/cs/0005031v3
cs-0006043v1 https://arxiv.org/pdf/cs/0006043v1
cs-0007004v1 https://arxiv.org/pdf/cs/0007004v1
cs-0010037v1 https://arxiv.org/pdf/cs/0010037v1
cs-0011012v3 https://arxiv.org/pdf/cs/0011012v3
cs-0011030v1 https://arxiv.org/pdf/cs/0011030v1
cs-0105022v1 https://arxiv.org/pdf/cs/0105022v1
cs-0106006v1 https://arxiv.org/pdf/cs/0106006v1
cs-0106007v1 https://arxiv.org/pdf/cs/0106007v1
cs-0106025v1 https://arxiv.org/pdf/cs/0106025v1
cs-0107002v1 https://arxiv.org/pdf/cs/0107002v1
cs-0109006v1 https://arxiv.org/pdf/cs/0109006v1
cs-0111060v1 https://arxiv.org/pdf/cs/0111060v1
cs-0112015v1 https://arxiv.org/pdf/cs/0112015v1
cs-0201022v2 https://arxiv.org/pdf/cs/0201022v2
cs-0202021v1 https://arxiv.org/pdf/cs/0202021v1
cs-0202022v1 https://arxiv.org/pdf/cs/0202022v1
cs-0202024v1 https://arxiv.org/pdf/cs/0202024v1
cs-0202025v1 https://arxiv.org/pdf/cs/0202025v1
cs-0202026v1 https://arxiv.org/pdf/cs/0202026v1
cs-0202031v1 https://arxiv.org/pdf/cs/0202031v1
cs-0202033v1 https://arxiv.org/pdf/cs/0202033v1
cs-0203002v1 https://arxiv.org/pdf/cs/0203002v1
cs-0203003v1 https://arxiv.org/pdf/cs/0203003v1
cs-0203004v1 https://arxiv.org/pdf/cs/0203004v1
cs-0203005v2 https://arxiv.org/pdf/cs/0203005v2
cs-0203007v1 https://arxiv.org/pdf/cs/0203007v1
cs-0204032v1 https://arxiv.org/pdf/cs/0204032v1
cs-0205014v1 https://arxiv.org/pdf/cs/0205014v1
cs-0206003v1 https://arxiv.org/pdf/cs/0206003v1
cs-0206041v2 https://arxiv.org/pdf/cs/0206041v2
cs-0207021v1 https://arxiv.org/pdf/cs/0207021v1
cs-0207023v2 https://arxiv.org/pdf/cs/0207023v2
cs-0207025v1 https://arxiv.org/pdf/cs/0207025v1
cs-0207029v2 https://arxiv.org/pdf/cs/0207029v2
cs-0207030v2 https://arxiv.org/pdf/cs/0207030v2
cs-0207042v1 https://arxiv.org/pdf/cs/0207042v1
cs-0207045v1 https://arxiv.org/pdf/cs/0207045v1
cs-0207056v1 https://arxiv.org/pdf/cs/0207056v1
cs-0207059v1 https://arxiv.org/pdf/cs/0207059v1
cs-0207060v1 https://arxiv.org/pdf/cs/0207060v1
cs-0207065v1 https://arxiv.org/pdf/cs/0207065v1
cs-0207067v1 https://arxiv.org/pdf/cs/0207067v1
cs-0207075v1 https://arxiv.org/pdf/cs/0207075v1
cs-0207083v1 https://arxiv.org/pdf/cs/0207083v1
cs-0208017v1 https://arxiv.org/pdf/cs/0208017v1
cs-0208019v1 https://arxiv.org/pdf/cs/0208019v1
cs-0208034v3 https://arxiv.org/pdf/cs/0208034v3
cs-0209019v1 https://arxiv.org/pdf/cs/0209019v1
cs-0209022v2 https://arxiv.org/pdf/cs/0209022v2
cs-0210004v1 https://arxiv.org/pdf/cs/0210004v1
cs-0211008v4 https://arxiv.org/pdf/cs/0211008v4
cs-0211027v1 https://arxiv.org/pdf/cs/0211027v1
cs-0211038v1 https://arxiv.org/pdf/cs/0211038v1
cs-0211039v1 https://arxiv.org/pdf/cs/0211039v1
cs-0211040v1 https://arxiv.org/pdf/cs/0211040v1
cs-0212025v1 https://arxiv.org/pdf/cs/0212025v1
cs-0301006v1 https://arxiv.org/pdf/cs/0301006v1
cs-0301010v2 https://arxiv.org/pdf/cs/0301010v2
cs-0301023v1 https://arxiv.org/pdf/cs/0301023v1
cs-0302029v1 https://arxiv.org/pdf/cs/0302029v1
cs-0302036v2 https://arxiv.org/pdf/cs/0302036v2
cs-0302039v1 https://arxiv.org/pdf/cs/0302039v1
cs-0303006v1 https://arxiv.org/pdf/cs/0303006v1
cs-0303009v2 https://arxiv.org/pdf/cs/0303009v2
cs-0303018v1 https://arxiv.org/pdf/cs/0303018v1
cs-0305001v1 https://arxiv.org/pdf/cs/0305001v1
cs-0305019v1 https://arxiv.org/pdf/cs/0305019v1
cs-0305044v2 https://arxiv.org/pdf/cs/0305044v2
cs-0306124v1 https://arxiv.org/pdf/cs/0306124v1
cs-0306135v1 https://arxiv.org/pdf/cs/0306135v1
cs-0307010v2 https://arxiv.org/pdf/cs/0307010v2
cs-0307025v1 https://arxiv.org/pdf/cs/0307025v1
cs-0307048v2 https://arxiv.org/pdf/cs/0307048v2
cs-0307050v1 https://arxiv.org/pdf/cs/0307050v1
cs-0307056v1 https://arxiv.org/pdf/cs/0307056v1
cs-0307063v1 https://arxiv.org/pdf/cs/0307063v1
cs-0308002v3 https://arxiv.org/pdf/cs/0308002v3
cs-0309025v1 https://arxiv.org/pdf/cs/0309025v1
cs-0310023v1 https://arxiv.org/pdf/cs/0310023v1
cs-0310044v1 https://arxiv.org/pdf/cs/0310044v1
cs-0310045v1 https://arxiv.org/pdf/cs/0310045v1
cs-0310047v1 https://arxiv.org/pdf/cs/0310047v1
cs-0310061v1 https://arxiv.org/pdf/cs/0310061v1
cs-0310062v1 https://arxiv.org/pdf/cs/0310062v1
cs-0311004v1 https://arxiv.org/pdf/cs/0311004v1
cs-0311007v1 https://arxiv.org/pdf/cs/0311007v1
cs-0311024v1 https://arxiv.org/pdf/cs/0311024v1
cs-0311026v1 https://arxiv.org/pdf/cs/0311026v1
cs-0311027v1 https://arxiv.org/pdf/cs/0311027v1
cs-0311045v1 https://arxiv.org/pdf/cs/0311045v1
cs-0311051v1 https://arxiv.org/pdf/cs/0311051v1
cs-0312020v1 https://arxiv.org/pdf/cs/0312020v1
cs-0312040v1 https://arxiv.org/pdf/cs/0312040v1
cs-0312045v1 https://arxiv.org/pdf/cs/0312045v1
cs-0312053v1 https://arxiv.org/pdf/cs/0312053v1
cs-0401009v1 https://arxiv.org/pdf/cs/0401009v1
cs-0402033v1 https://arxiv.org/pdf/cs/0402033v1
cs-0402035v1 https://arxiv.org/pdf/cs/0402035v1
cs-0402057v2 https://arxiv.org/pdf/cs/0402057v2
cs-0403002v2 https://arxiv.org/pdf/cs/0403002v2
cs-0403006v1 https://arxiv.org/pdf/cs/0403006v1
cs-0404011v1 https://arxiv.org/pdf/cs/0404011v1
cs-0404012v1 https://arxiv.org/pdf/cs/0404012v1
cs-0404051v1 https://arxiv.org/pdf/cs/0404051v1
cs-0405008v1 https://arxiv.org/pdf/cs/0405008v1
cs-0405009v1 https://arxiv.org/pdf/cs/0405009v1
cs-0405010v1 https://arxiv.org/pdf/cs/0405010v1
cs-0405011v1 https://arxiv.org/pdf/cs/0405011v1
cs-0405012v1 https://arxiv.org/pdf/cs/0405012v1
cs-0405013v1 https://arxiv.org/pdf/cs/0405013v1
cs-0405014v1 https://arxiv.org/pdf/cs/0405014v1
cs-0405016v1 https://arxiv.org/pdf/cs/0405016v1
cs-0405017v1 https://arxiv.org/pdf/cs/0405017v1
cs-0405018v1 https://arxiv.org/pdf/cs/0405018v1
cs-0405019v1 https://arxiv.org/pdf/cs/0405019v1
cs-0405024v1 https://arxiv.org/pdf/cs/0405024v1
cs-0405025v1 https://arxiv.org/pdf/cs/0405025v1
cs-0405026v1 https://arxiv.org/pdf/cs/0405026v1
cs-0405028v1 https://arxiv.org/pdf/cs/0405028v1
cs-0405030v1 https://arxiv.org/pdf/cs/0405030v1
cs-0405031v1 https://arxiv.org/pdf/cs/0405031v1
cs-0405032v1 https://arxiv.org/pdf/cs/0405032v1
cs-0405033v1 https://arxiv.org/pdf/cs/0405033v1
cs-0405049v1 https://arxiv.org/pdf/cs/0405049v1
cs-0405050v1 https://arxiv.org/pdf/cs/0405050v1
cs-0405051v1 https://arxiv.org/pdf/cs/0405051v1
cs-0405052v1 https://arxiv.org/pdf/cs/0405052v1
cs-0405071v1 https://arxiv.org/pdf/cs/0405071v1
cs-0405090v1 https://arxiv.org/pdf/cs/0405090v1
cs-0405106v1 https://arxiv.org/pdf/cs/0405106v1
cs-0405113v2 https://arxiv.org/pdf/cs/0405113v2
cs-0406038v1 https://arxiv.org/pdf/cs/0406038v1
cs-0407008v1 https://arxiv.org/pdf/cs/0407008v1
cs-0407037v1 https://arxiv.org/pdf/cs/0407037v1
cs-0407040v1 https://arxiv.org/pdf/cs/0407040v1
cs-0407042v1 https://arxiv.org/pdf/cs/0407042v1
cs-0407044v1 https://arxiv.org/pdf/cs/0407044v1
cs-0408010v5 https://arxiv.org/pdf/cs/0408010v5
cs-0408021v2 https://arxiv.org/pdf/cs/0408021v2
cs-0408044v1 https://arxiv.org/pdf/cs/0408044v1
cs-0408055v1 https://arxiv.org/pdf/cs/0408055v1
cs-0408064v3 https://arxiv.org/pdf/cs/0408064v3
cs-0409007v1 https://arxiv.org/pdf/cs/0409007v1
cs-0409040v3 https://arxiv.org/pdf/cs/0409040v3
cs-0410014v1 https://arxiv.org/pdf/cs/0410014v1
cs-0410033v2 https://arxiv.org/pdf/cs/0410033v2
cs-0410049v1 https://arxiv.org/pdf/cs/0410049v1
cs-0410050v1 https://arxiv.org/pdf/cs/0410050v1
cs-0411015v1 https://arxiv.org/pdf/cs/0411015v1
cs-0411034v2 https://arxiv.org/pdf/cs/0411034v2
cs-0411071v1 https://arxiv.org/pdf/cs/0411071v1
cs-0411072v1 https://arxiv.org/pdf/cs/0411072v1
cs-0412091v1 https://arxiv.org/pdf/cs/0412091v1
cs-0501068v1 https://arxiv.org/pdf/cs/0501068v1
cs-0501072v1 https://arxiv.org/pdf/cs/0501072v1
cs-0501084v1 https://arxiv.org/pdf/cs/0501084v1
cs-0501086v1 https://arxiv.org/pdf/cs/0501086v1
cs-0501089v1 https://arxiv.org/pdf/cs/0501089v1
cs-0501093v1 https://arxiv.org/pdf/cs/0501093v1
cs-0501094v2 https://arxiv.org/pdf/cs/0501094v2
cs-0501095v1 https://arxiv.org/pdf/cs/0501095v1
cs-0501096v1 https://arxiv.org/pdf/cs/0501096v1
cs-0502060v1 https://arxiv.org/pdf/cs/0502060v1
cs-0504064v1 https://arxiv.org/pdf/cs/0504064v1
cs-0504065v1 https://arxiv.org/pdf/cs/0504065v1
cs-0504066v1 https://arxiv.org/pdf/cs/0504066v1
cs-0504071v1 https://arxiv.org/pdf/cs/0504071v1
cs-0505018v1 https://arxiv.org/pdf/cs/0505018v1
cs-0505081v1 https://arxiv.org/pdf/cs/0505081v1
cs-0506031v1 https://arxiv.org/pdf/cs/0506031v1
cs-0507010v1 https://arxiv.org/pdf/cs/0507010v1
cs-0507023v1 https://arxiv.org/pdf/cs/0507023v1
cs-0507029v1 https://arxiv.org/pdf/cs/0507029v1
cs-0508132v1 https://arxiv.org/pdf/cs/0508132v1
cs-0509011v1 https://arxiv.org/pdf/cs/0509011v1
cs-0509033v1 https://arxiv.org/pdf/cs/0509033v1
cs-0510050v1 https://arxiv.org/pdf/cs/0510050v1
cs-0510062v1 https://arxiv.org/pdf/cs/0510062v1
cs-0510063v1 https://arxiv.org/pdf/cs/0510063v1
cs-0510079v2 https://arxiv.org/pdf/cs/0510079v2
cs-0510083v1 https://arxiv.org/pdf/cs/0510083v1
cs-0510091v1 https://arxiv.org/pdf/cs/0510091v1
cs-0511004v1 https://arxiv.org/pdf/cs/0511004v1
cs-0511015v2 https://arxiv.org/pdf/cs/0511015v2
cs-0511091v1 https://arxiv.org/pdf/cs/0511091v1
cs-0512045v2 https://arxiv.org/pdf/cs/0512045v2
cs-0512047v2 https://arxiv.org/pdf/cs/0512047v2
cs-0512099v1 https://arxiv.org/pdf/cs/0512099v1
cs-0601001v2 https://arxiv.org/pdf/cs/0601001v2
cs-0601031v1 https://arxiv.org/pdf/cs/0601031v1
cs-0601052v1 https://arxiv.org/pdf/cs/0601052v1
cs-0601109v3 https://arxiv.org/pdf/cs/0601109v3
cs-0602022v1 https://arxiv.org/pdf/cs/0602022v1
cs-0602031v1 https://arxiv.org/pdf/cs/0602031v1
cs-0603025v2 https://arxiv.org/pdf/cs/0603025v2
cs-0603034v1 https://arxiv.org/pdf/cs/0603034v1
cs-0603038v2 https://arxiv.org/pdf/cs/0603038v2
cs-0603081v1 https://arxiv.org/pdf/cs/0603081v1
cs-0603120v1 https://arxiv.org/pdf/cs/0603120v1
cs-0604009v1 https://arxiv.org/pdf/cs/0604009v1
cs-0604042v1 https://arxiv.org/pdf/cs/0604042v1
cs-0604070v2 https://arxiv.org/pdf/cs/0604070v2
cs-0604086v1 https://arxiv.org/pdf/cs/0604086v1
cs-0605012v2 https://arxiv.org/pdf/cs/0605012v2
cs-0605017v1 https://arxiv.org/pdf/cs/0605017v1
cs-0605055v1 https://arxiv.org/pdf/cs/0605055v1
cs-0605108v2 https://arxiv.org/pdf/cs/0605108v2
cs-0605123v1 https://arxiv.org/pdf/cs/0605123v1
cs-0606020v2 https://arxiv.org/pdf/cs/0606020v2
cs-0606029v1 https://arxiv.org/pdf/cs/0606029v1
cs-0606066v1 https://arxiv.org/pdf/cs/0606066v1
cs-0606081v3 https://arxiv.org/pdf/cs/0606081v3
cs-0607005v2 https://arxiv.org/pdf/cs/0607005v2
cs-0607071v1 https://arxiv.org/pdf/cs/0607071v1
cs-0607084v1 https://arxiv.org/pdf/cs/0607084v1
cs-0607086v1 https://arxiv.org/pdf/cs/0607086v1
cs-0607143v1 https://arxiv.org/pdf/cs/0607143v1
cs-0607147v2 https://arxiv.org/pdf/cs/0607147v2
cs-0608002v1 https://arxiv.org/pdf/cs/0608002v1
cs-0608019v1 https://arxiv.org/pdf/cs/0608019v1
cs-0608028v1 https://arxiv.org/pdf/cs/0608028v1
cs-0609111v2 https://arxiv.org/pdf/cs/0609111v2
cs-0609132v1 https://arxiv.org/pdf/cs/0609132v1
cs-0609136v1 https://arxiv.org/pdf/cs/0609136v1
cs-0609142v1 https://arxiv.org/pdf/cs/0609142v1
cs-0610006v2 https://arxiv.org/pdf/cs/0610006v2
cs-0610015v1 https://arxiv.org/pdf/cs/0610015v1
cs-0610023v1 https://arxiv.org/pdf/cs/0610023v1
cs-0610043v1 https://arxiv.org/pdf/cs/0610043v1
cs-0610060v1 https://arxiv.org/pdf/cs/0610060v1
cs-0610111v3 https://arxiv.org/pdf/cs/0610111v3
cs-0610140v1 https://arxiv.org/pdf/cs/0610140v1
cs-0610156v1 https://arxiv.org/pdf/cs/0610156v1
cs-0610165v1 https://arxiv.org/pdf/cs/0610165v1
cs-0610175v1 https://arxiv.org/pdf/cs/0610175v1
cs-0611047v1 https://arxiv.org/pdf/cs/0611047v1
cs-0611085v1 https://arxiv.org/pdf/cs/0611085v1
cs-0611118v2 https://arxiv.org/pdf/cs/0611118v2
cs-0611135v1 https://arxiv.org/pdf/cs/0611135v1
cs-0611138v1 https://arxiv.org/pdf/cs/0611138v1
cs-0611141v1 https://arxiv.org/pdf/cs/0611141v1
cs-0612056v1 https://arxiv.org/pdf/cs/0612056v1
cs-0612057v1 https://arxiv.org/pdf/cs/0612057v1
cs-0612068v1 https://arxiv.org/pdf/cs/0612068v1
cs-0612109v2 https://arxiv.org/pdf/cs/0612109v2
cs-0701013v1 https://arxiv.org/pdf/cs/0701013v1
cs-0701184v2 https://arxiv.org/pdf/cs/0701184v2
cs-0702028v2 https://arxiv.org/pdf/cs/0702028v2
cs-0702170v1 https://arxiv.org/pdf/cs/0702170v1
cs-0703060v1 https://arxiv.org/pdf/cs/0703060v1
cs-0703124v1 https://arxiv.org/pdf/cs/0703124v1
cs-0703130v1 https://arxiv.org/pdf/cs/0703130v1
cs-0703156v1 https://arxiv.org/pdf/cs/0703156v1
cs-9503101v1 https://arxiv.org/pdf/cs/9503101v1
cs-9710101v1 https://arxiv.org/pdf/cs/9710101v1
cs-9808001v1 https://arxiv.org/pdf/cs/9808001v1
cs-9808005v1 https://arxiv.org/pdf/cs/9808005v1
cs-9808006v2 https://arxiv.org/pdf/cs/9808006v2
cs-9808007v1 https://arxiv.org/pdf/cs/9808007v1
cs-9809013v1 https://arxiv.org/pdf/cs/9809013v1
cs-9809032v1 https://arxiv.org/pdf/cs/9809032v1
cs-9809034v1 https://arxiv.org/pdf/cs/9809034v1
cs-9809108v1 https://arxiv.org/pdf/cs/9809108v1
cs-9809121v1 https://arxiv.org/pdf/cs/9809121v1
cs-9810005v1 https://arxiv.org/pdf/cs/9810005v1
cs-9810018v1 https://arxiv.org/pdf/cs/9810018v1
cs-9811029v1 https://arxiv.org/pdf/cs/9811029v1
cs-9812022v1 https://arxiv.org/pdf/cs/9812022v1
cs-9901001v1 https://arxiv.org/pdf/cs/9901001v1
cs-9901002v1 https://arxiv.org/pdf/cs/9901002v1
cs-9901003v1 https://arxiv.org/pdf/cs/9901003v1
cs-9901012v1 https://arxiv.org/pdf/cs/9901012v1
cs-9901016v1 https://arxiv.org/pdf/cs/9901016v1
cs-9904004v1 https://arxiv.org/pdf/cs/9904004v1

In [9]:
new_df.head()

,id,title,published_date,authors,first_author,summary,pdf_link
0,cs-9308101v1,Dynamic Backtracking,8/1/93,['M. L. Ginsberg'],'M. L. Ginsberg',Because of their occasional need to return to ...,https://arxiv.org/pdf/cs/9308101v1
1,cs-9308102v1,A Market-Oriented Programming Environment and ...,8/1/93,['M. P. Wellman'],'M. P. Wellman',Market price systems constitute a well-underst...,https://arxiv.org/pdf/cs/9308102v1
2,cs-9309101v1,An Empirical Analysis of Search in GSAT,9/1/93,"['I. P. Gent', 'T. Walsh']",'I. P. Gent',We describe an extensive study of search in GS...,https://arxiv.org/pdf/cs/9309101v1
3,cs-9311101v1,The Difficulties of Learning Logic Programs wi...,11/1/93,"['F. Bergadano', 'D. Gunetti', 'U. Trinchero']",'F. Bergadano',As real logic programmers normally use cut (!)...,https://arxiv.org/pdf/cs/9311101v1
4,cs-9311102v1,Software Agents: Completing Patterns and Const...,11/1/93,"['J. C. Schlimmer', 'L. A. Hermens']",'J. C. Schlimmer',To support the goal of allowing users to recor...,https://arxiv.org/pdf/cs/9311102v1

In [10]:
final_df = new_df.loc[
    new_df['id'].str.startswith('cs-', na=False),
    ['id', 'title', 'published_date', 'summary','authors', 'first_author', 'pdf_link']
]

In [11]:
print(final_df)

                  id                                              title  \
0       cs-9308101v1                               Dynamic Backtracking
1       cs-9308102v1  A Market-Oriented Programming Environment and ...
2       cs-9309101v1            An Empirical Analysis of Search in GSAT
3       cs-9311101v1  The Difficulties of Learning Logic Programs wi...
4       cs-9311102v1  Software Agents: Completing Patterns and Const...
...              ...                                                ...
113297  cs-0611113v1  An Anthological Review of Research Utilizing M...
113298  cs-0701135v1                Complex networks and human language
113299  cs-0701181v1             A Note on Local Ultrametricity in Text
113300  cs-0701194v1  Menzerath-Altmann Law for Syntactic Structures...
113301  cs-0702081v1  Random Sentences from a Generalized Phrase-Str...

       published_date                                            summary  \
0              8/1/93  Because of their occasional need to return to ...
1              8/1/93  Market price systems constitute a well-underst...
2              9/1/93  We describe an extensive study of search in GS...
3             11/1/93  As real logic programmers normally use cut (!)...
4             11/1/93  To support the goal of allowing users to recor...
...               ...                                                ...
113297       11/22/06  MontyLingua, an integral part of ConceptNet wh...
113298        1/22/07  This paper introduces how human languages can ...
113299        1/27/07  High dimensional, sparsely populated data spac...
113300        1/30/07  In the paper, the definition of clause suitabl...
113301        2/14/07  In numerous domains in cognitive science it is...

                                               authors       first_author  \
0                                   ['M. L. Ginsberg']   'M. L. Ginsberg'
1                                    ['M. P. Wellman']    'M. P. Wellman'
2                           ['I. P. Gent', 'T. Walsh']       'I. P. Gent'
3       ['F. Bergadano', 'D. Gunetti', 'U. Trinchero']     'F. Bergadano'
4                 ['J. C. Schlimmer', 'L. A. Hermens']  'J. C. Schlimmer'
...                                                ...                ...
113297                             ['Maurice HT Ling']  'Maurice HT Ling'
113298                                   ['Jinyun KE']        'Jinyun KE'
113299                               ['Fionn Murtagh']    'Fionn Murtagh'
113300            ['Solomija Buk', 'Andrij Rovenchak']     'Solomija Buk'
113301                                   ['Rick Dale']        'Rick Dale'

                                  pdf_link
0       https://arxiv.org/pdf/cs/9308101v1
1       https://arxiv.org/pdf/cs/9308102v1
2       https://arxiv.org/pdf/cs/9309101v1
3       https://arxiv.org/pdf/cs/9311101v1
4       https://arxiv.org/pdf/cs/9311102v1
...                                    ...
113297  https://arxiv.org/pdf/cs/0611113v1
113298  https://arxiv.org/pdf/cs/0701135v1
113299  https://arxiv.org/pdf/cs/0701181v1
113300  https://arxiv.org/pdf/cs/0701194v1
113301  https://arxiv.org/pdf/cs/0702081v1

[1325 rows x 7 columns]

In [12]:
final_df.to_csv("new_final_data.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'new_final_data.csv'